server {

    listen 80;

    server_name localhost;


    # USER SERVICE

    location /api/users/ {

        proxy_pass http://user-service:8001/users/;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

    }


    # PRODUCT SERVICE

    location /api/products/ {

        proxy_pass http://product-service:8002/products/;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

    }


    # ORDER SERVICE

    location /api/orders/ {

        proxy_pass http://order-service:8003/orders/;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

    }


    # CHAT SERVICE

    location /api/chat/ {

        proxy_pass http://chat-service:8004/chat/;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

    }

}
