events {}

http {

    server {

        listen 80;


        # Internal authentication request
        location = /auth {

            internal;

            proxy_pass http://user-service:8001/users/verify/;

            proxy_pass_request_body off;

            proxy_set_header Content-Length "";

            proxy_set_header Authorization $http_authorization;
        }



        # User Service
        location /api/users/ {

            proxy_pass http://user-service:8001/users/;
        }



        # Product Service
        location /api/products/ {

            auth_request /auth;

            auth_request_set $user_id $upstream_http_x_user_id;
            auth_request_set $user_email $upstream_http_x_user_email;


            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-User-Email $user_email;


            proxy_pass http://product-service:8002/products/;
        }



        # Order Service
        location /api/orders/ {

            auth_request /auth;


            auth_request_set $user_id $upstream_http_x_user_id;
            auth_request_set $user_email $upstream_http_x_user_email;


            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-User-Email $user_email;


            proxy_pass http://order-service:8003/orders/;
        }



        # Chat WebSocket Service
        
        location /ws/chat/ {

         auth_request /auth;


         auth_request_set $user_id $upstream_http_x_user_id;
         auth_request_set $user_email $upstream_http_x_user_email;
         auth_request_set $user_role $upstream_http_x_user_role;


         proxy_set_header X-User-Id $user_id;
         proxy_set_header X-User-Email $user_email;
         proxy_set_header X-User-Role $user_role;


         proxy_pass http://chat-service:8004/ws/chat/;


         proxy_http_version 1.1;

         proxy_set_header Upgrade $http_upgrade;

         proxy_set_header Connection "upgrade";

         proxy_set_header Host $host;

        }