events {}

http {

    server {

        listen 80;

        # Internal authentication request
        location = /auth {

            internal;

            proxy_pass http://127.0.0.1:8001/users/verify/;

            proxy_pass_request_body off;

            proxy_set_header Content-Length "";

            proxy_set_header Authorization $http_authorization;
        }

        # User Service
        location /api/users/ {

            proxy_pass http://127.0.0.1:8001/;
        }

        # Product Service
        location /api/products/ {

            auth_request /auth;

            auth_request_set $user_id $upstream_http_x_user_id;
            auth_request_set $user_email $upstream_http_x_user_email;

            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-User-Email $user_email;

            proxy_pass http://127.0.0.1:8002/;
        }

        # Order Service
        location /api/orders/ {

            auth_request /auth;

            auth_request_set $user_id $upstream_http_x_user_id;
            auth_request_set $user_email $upstream_http_x_user_email;

            proxy_set_header X-User-Id $user_id;
            proxy_set_header X-User-Email $user_email;

            proxy_pass http://127.0.0.1:8003/;
        }

    }

}