# Generated by Django 6.0.6 on 2026-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
